In [ ]:
import torch
import cv2
import numpy as np

print("Torch version:", torch.__version__)
print("CUDA version:", torch.version.cuda)
print("Is CUDA available?:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))

Torch version: 2.5.1+cu121
CUDA version: 12.1
Is CUDA available?: True
GPU name: NVIDIA GeForce RTX 3050 Ti Laptop GPU

In [2]:
import pandas as pd 

path = "D:\BODYPAR\Graphonomy\Graphonomy-master\segmentation_summary.csv"
data = pd.read_csv(path)

In [10]:
import os
img_root = "D:/BODYPAR/Graphonomy/Graphonomy-master/img"
img_output = "D:/BODYPAR/Graphonomy/Graphonomy-master/img_par"
img_thermal = "D:/BODYPAR/Graphonomy/Graphonomy-master/img_thermal"
jpg_files = [f for f in os.listdir(img_root) if f.lower().endswith("flir.jpg")]
print(jpg_files)

['P010_1_FLIR.jpg', 'P010_2_FLIR.jpg', 'P011_1_FLIR.jpg', 'P011_2_FLIR.jpg', 'P012_1_FLIR.jpg', 'P012_2_FLIR.jpg', 'P013_1_FLIR.jpg', 'P013_2_FLIR.jpg', 'P014_1_FLIR.jpg', 'P015_1_FLIR.jpg', 'P015_2_FLIR.jpg', 'P016_1_FLIR.jpg', 'P017_1_FLIR.jpg', 'P017_2_FLIR.jpg', 'P018_1_FLIR.jpg', 'P018_2_FLIR.jpg', 'P019_1_FLIR.jpg', 'P019_2_FLIR.jpg', 'P020_1_FLIR.jpg', 'P020_2_FLIR.jpg', 'P021_1_FLIR.jpg', 'P021_2_FLIR.jpg', 'P022_1_FLIR.jpg', 'P022_2_FLIR.jpg', 'P023_1_FLIR.jpg', 'P023_2_FLIR.jpg', 'P024_1_FLIR.jpg', 'P024_2_FLIR.jpg', 'P025_1_FLIR.jpg', 'P025_2_FLIR.jpg', 'P026_1_FLIR.jpg', 'P026_2_FLIR.jpg', 'P027_1_FLIR.jpg', 'P027_2_FLIR.jpg', 'P028_1_FLIR.jpg', 'P028_2_FLIR.jpg', 'P029_1_FLIR.jpg', 'P029_2_FLIR.jpg', 'P030_1_FLIR.jpg', 'P031_1_FLIR.jpg', 'P031_2_FLIR.jpg', 'P032_1_FLIR.jpg', 'P032_2_FLIR.jpg', 'P033_1_FLIR.jpg', 'P033_2_FLIR.jpg', 'P034_1_FLIR.jpg', 'P034_2_FLIR.jpg', 'P036_1_FLIR.jpg', 'P036_2_FLIR.jpg', 'P037_1_FLIR.jpg', 'P037_2_FLIR.jpg', 'P038_1_FLIR.jpg', 'P038_2_FLIR.jpg', 'P039_1_FLIR.jpg', 'P039_2_FLIR.jpg', 'P040_1_FLIR.jpg', 'P040_2_FLIR.jpg', 'P041_1_FLIR.jpg', 'P041_2_FLIR.jpg', 'P042_1_FLIR.jpg', 'P042_2_FLIR.jpg', 'P043_1_FLIR.jpg', 'P043_2_FLIR.jpg', 'P044_1_FLIR.jpg', 'P044_2_FLIR.jpg', 'P045_1_FLIR.jpg', 'P045_2_FLIR.jpg', 'P046_1_FLIR.jpg', 'P046_2_FLIR.jpg', 'P047_1_FLIR.jpg', 'P047_2_FLIR.jpg', 'P048_1_FLIR.jpg', 'P049_1_FLIR.jpg', 'P049_2_FLIR.jpg', 'P050_1_FLIR.jpg', 'P050_2_FLIR.jpg', 'P051_1_FLIR.jpg', 'P051_2_FLIR.jpg', 'P052_1_FLIR.jpg', 'P052_2_FLIR.jpg', 'P053_1_FLIR.jpg', 'P053_2_FLIR.jpg', 'P054_1_FLIR.jpg', 'P055_1_FLIR.jpg', 'P055_2_FLIR.jpg', 'P056_1_FLIR.jpg', 'P056_2_FLIR.jpg', 'P057_1_FLIR.jpg', 'P058_1_FLIR.jpg', 'P059_1_FLIR.jpg', 'P059_2_FLIR.jpg', 'P060_1_FLIR.jpg', 'P060_2_FLIR.jpg', 'P061_1_FLIR.jpg', 'P061_2_FLIR.jpg', 'P062_1_FLIR.jpg', 'P062_2_FLIR.jpg', 'P063_1_FLIR.jpg', 'P063_2_FLIR.jpg', 'P064_1_FLIR.jpg', 'P064_2_FLIR.jpg', 'P065_1_FLIR.jpg', 'P065_2_FLIR.jpg', 'P066_1_FLIR.jpg', 'P066_2_FLIR.jpg', 'P067_1_FLIR.jpg', 'P067_2_FLIR.jpg', 'P069_1_FLIR.jpg', 'P070_1_FLIR.jpg', 'P071_1_FLIR.jpg', 'P071_2_FLIR.jpg', 'P072_1_FLIR.jpg', 'P072_2_FLIR.jpg', 'P073_1_FLIR.jpg', 'P073_2_FLIR.jpg', 'P074_1_FLIR.jpg', 'P074_2_FLIR.jpg', 'P075_1_FLIR.jpg', 'P075_2_FLIR.jpg', 'P076_1_FLIR.jpg', 'P076_2_FLIR.jpg', 'P077_1_FLIR.jpg', 'P077_2_FLIR.jpg', 'P078_1_FLIR.jpg', 'P078_2_FLIR.jpg', 'P079_1_FLIR.jpg', 'P080_1_FLIR.jpg', 'P080_2_FLIR.jpg', 'P081_1_FLIR.jpg', 'P081_2_FLIR.jpg', 'P082_1_FLIR.jpg', 'P083_1_FLIR.jpg', 'P083_2_FLIR.jpg', 'P084_1_FLIR.jpg', 'P084_2_FLIR.jpg', 'P085_1_FLIR.jpg', 'P085_2_FLIR.jpg', 'P086_1_FLIR.jpg', 'P086_2_FLIR.jpg', 'P087_1_FLIR.jpg', 'P087_2_FLIR.jpg', 'P088_1_FLIR.jpg', 'P088_2_FLIR.jpg', 'P089_1_FLIR.jpg', 'P090_1_FLIR.jpg', 'P090_2_FLIR.jpg', 'P091_1_FLIR.jpg', 'P091_2_FLIR.jpg', 'P092_1_FLIR.jpg', 'P092_2_FLIR.jpg', 'P093_1_FLIR.jpg', 'P093_2_FLIR.jpg', 'P094_1_FLIR.jpg', 'P094_2_FLIR.jpg', 'P095_1_FLIR.jpg', 'P095_2_FLIR.jpg', 'P096_1_FLIR.jpg', 'P096_2_FLIR.jpg', 'P097_1_FLIR.jpg', 'P098_1_FLIR.jpg', 'P098_2_FLIR.jpg', 'P099_1_FLIR.jpg', 'P099_2_FLIR.jpg', 'P100_1_FLIR.jpg', 'P100_2_FLIR.jpg', 'P101_1_FLIR.jpg', 'P101_2_FLIR.jpg', 'P103_1_FLIR.jpg', 'P103_2_FLIR.jpg', 'P105_1_FLIR.jpg', 'P105_2_FLIR.jpg', 'P106_1_FLIR.jpg', 'P106_2_FLIR.jpg', 'P107_1_FLIR.jpg', 'P107_2_FLIR.jpg', 'P108_1_FLIR.jpg', 'P108_2_FLIR.jpg', 'P109_1_FLIR.jpg', 'P109_2_FLIR.jpg', 'P110_1_FLIR.jpg', 'P110_2_FLIR.jpg', 'P111_1_FLIR.jpg', 'P111_2_FLIR.jpg', 'P112_1_FLIR.jpg', 'P112_2_FLIR.jpg', 'P113_1_FLIR.jpg', 'P113_2_FLIR.jpg', 'P114_1_FLIR.jpg', 'P114_2_FLIR.jpg', 'P115_1_FLIR.jpg', 'P115_2_FLIR.jpg', 'P116_1_FLIR.jpg', 'P116_2_FLIR.jpg', 'P117_1_FLIR.jpg', 'P117_2_FLIR.jpg', 'P118_1_FLIR.jpg', 'P118_2_FLIR.jpg', 'P119_1_FLIR.jpg', 'P120_1_FLIR.jpg', 'P120_2_FLIR.jpg', 'P121_1_FLIR.jpg', 'P121_2_FLIR.jpg', 'P122_1_FLIR.jpg', 'P122_2_FLIR.jpg', 'P123_1_FLIR.jpg', 'P124_1_FLIR.jpg', 'P124_2_FLIR.jpg', 'P125_1_FLIR.jpg', 'P125_2_FLIR.jpg', 'P126_1_FLIR.jpg', 'P126_2_FLIR.jpg', 'P127_1_FLIR.jpg', 'P127_2_FLIR.jpg', 'P128_1_FLIR.jpg', 'P128_2_FLIR.jpg', 'P129_1_FLIR.jpg', 'P130_1_FLIR.jpg', 'P130_2_FLIR.jpg', 'P131_1_FLIR.jpg', 'P131_2_FLIR.jpg', 'P132_1_FLIR.jpg', 'P132_2_FLIR.jpg', 'P133_1_FLIR.jpg', 'P133_2_FLIR.jpg', 'P134_1_FLIR.jpg', 'P134_2_FLIR.jpg', 'P135_1_FLIR.jpg', 'P135_2_FLIR.jpg', 'P136_1_FLIR.jpg', 'P136_2_FLIR.jpg', 'P137_1_FLIR.jpg', 'P137_2_FLIR.jpg', 'P138_1_FLIR.jpg', 'P138_2_FLIR.jpg', 'P139_1_FLIR.jpg', 'P139_2_FLIR.jpg', 'P140_1_FLIR.jpg', 'P140_2_FLIR.jpg', 'P141_1_FLIR.jpg', 'P141_2_FLIR.jpg', 'P142_1_FLIR.jpg', 'P142_2_FLIR.jpg', 'P143_1_FLIR.jpg', 'P144_1_FLIR.jpg', 'P144_2_FLIR.jpg', 'P145_1_FLIR.jpg', 'P145_2_FLIR.jpg', 'P146_1_FLIR.jpg', 'P146_2_FLIR.jpg', 'P147_1_FLIR.jpg', 'P147_2_FLIR.jpg', 'P148_1_FLIR.jpg', 'P148_2_FLIR.jpg', 'P149_1_FLIR.jpg', 'P149_2_FLIR.jpg', 'P150_1_FLIR.jpg', 'P150_2_FLIR.jpg', 'P151_1_FLIR.jpg', 'P151_2_FLIR.jpg', 'P152_1_FLIR.jpg', 'P152_2_FLIR.jpg', 'P153_1_FLIR.jpg', 'P154_1_FLIR.jpg', 'P154_2_FLIR.jpg', 'P155_1_FLIR.jpg', 'P155_2_FLIR.jpg', 'P156_1_FLIR.jpg', 'P156_2_FLIR.jpg', 'P157_1_FLIR.jpg', 'P157_2_FLIR.jpg', 'P158_1_FLIR.jpg', 'P159_1_FLIR.jpg', 'P160_1_FLIR.jpg', 'P160_2_FLIR.jpg', 'P161_1_FLIR.jpg', 'P161_2_FLIR.jpg', 'P162_1_FLIR.jpg', 'P162_2_FLIR.jpg', 'P164_1_FLIR.jpg', 'P164_2_FLIR.jpg', 'P166_1_FLIR.jpg', 'P167_1_FLIR.jpg', 'P167_2_FLIR.jpg', 'P168_1_FLIR.jpg', 'P168_2_FLIR.jpg', 'P169_1_FLIR.jpg', 'P169_2_FLIR.jpg', 'P170_1_FLIR.jpg', 'P170_2_FLIR.jpg', 'P171_1_FLIR.jpg', 'P171_2_FLIR.jpg', 'P172_1_FLIR.jpg', 'P172_2_FLIR.jpg', 'P173_1_FLIR.jpg', 'P173_2_FLIR.jpg', 'P174_1_FLIR.jpg', 'P174_2_FLIR.jpg', 'P175_1_FLIR.jpg', 'P175_2_FLIR.jpg', 'P176_1_FLIR.jpg', 'P176_2_FLIR.jpg', 'P177_1_FLIR.jpg', 'P178_1_FLIR.jpg', 'P179_1_FLIR.jpg', 'P180_1_FLIR.jpg', 'P181_1_FLIR.jpg', 'P181_2_FLIR.jpg', 'P182_1_FLIR.jpg', 'P182_2_FLIR.jpg', 'P183_1_FLIR.jpg', 'P184_1_FLIR.jpg', 'P184_2_FLIR.jpg', 'P185_1_FLIR.jpg', 'P185_2_FLIR.jpg', 'P186_1_FLIR.jpg', 'P186_2_FLIR.jpg', 'P187_1_FLIR.jpg', 'P187_2_FLIR.jpg', 'P188_1_FLIR.jpg', 'P188_2_FLIR.jpg', 'P189_1_FLIR.jpg', 'P189_2_FLIR.jpg', 'P190_1_FLIR.jpg', 'P190_2_FLIR.jpg', 'P191_1_FLIR.jpg', 'P191_2_FLIR.jpg', 'P192_1_FLIR.jpg', 'P192_2_FLIR.jpg', 'P193_1_FLIR.jpg', 'P194_1_FLIR.jpg', 'P195_1_FLIR.jpg', 'P196_1_FLIR.jpg', 'P196_2_FLIR.jpg', 'P197_1_FLIR.jpg', 'P197_2_FLIR.jpg', 'P198_1_FLIR.jpg', 'P198_2_FLIR.jpg', 'P199_1_FLIR.jpg', 'P199_2_FLIR.jpg', 'P200_1_FLIR.jpg', 'P202_1_FLIR.jpg', 'P202_2_FLIR.jpg', 'P203_1_FLIR.jpg', 'P204_1_FLIR.jpg', 'P204_2_FLIR.jpg', 'P205_1_FLIR.jpg', 'P205_2_FLIR.jpg', 'P206_1_FLIR.jpg', 'P207_1_FLIR.jpg', 'P208_1_FLIR.jpg', 'P209_1_FLIR.jpg', 'P209_2_FLIR.jpg', 'P210_1_FLIR.jpg', 'P210_2_FLIR.jpg', 'P211_2_FLIR.jpg', 'P212_1_FLIR.jpg', 'P212_2_FLIR.jpg', 'P213_1_FLIR.jpg', 'P213_2_FLIR.jpg', 'P214_1_FLIR.jpg', 'P214_2_FLIR.jpg', 'P215_1_FLIR.jpg', 'P215_2_FLIR.jpg', 'P216_1_FLIR.jpg', 'P216_2_FLIR.jpg', 'P217_1_FLIR.jpg', 'P217_2_FLIR.jpg', 'P218_1_FLIR.jpg', 'P218_2_FLIR.jpg', 'P219_1_FLIR.jpg', 'P219_2_FLIR.jpg', 'P220_1_FLIR.jpg', 'P221_1_FLIR.jpg', 'P221_2_FLIR.jpg', 'P222_1_FLIR.jpg', 'P222_2_FLIR.jpg', 'P223_1_FLIR.jpg', 'P223_2_FLIR.jpg', 'P224_1_FLIR.jpg', 'P224_2_FLIR.jpg', 'P225_1_FLIR.jpg', 'P225_2_FLIR.jpg', 'P226_1_FLIR.jpg', 'P227_1_FLIR.jpg', 'P227_2_FLIR.jpg', 'P228_1_FLIR.jpg', 'P229_1_FLIR.jpg', 'P229_2_FLIR.jpg', 'P230_1_FLIR.jpg', 'P231_1_FLIR.jpg', 'P231_2_FLIR.jpg', 'P232_1_FLIR.jpg', 'P232_2_FLIR.jpg', 'P233_1_FLIR.jpg', 'P234_1_FLIR.jpg', 'P235_1_FLIR.jpg', 'P235_2_FLIR.jpg', 'P236_1_FLIR.jpg', 'P236_2_FLIR.jpg', 'P237_1_FLIR.jpg', 'P238_1_FLIR.jpg', 'P239_1_FLIR.jpg', 'P239_2_FLIR.jpg', 'P240_1_FLIR.jpg', 'P240_2_FLIR.jpg', 'P241_1_FLIR.jpg', 'P241_2_FLIR.jpg', 'P242_1_FLIR.jpg', 'P242_2_FLIR.jpg', 'P243_1_FLIR.jpg', 'P243_2_FLIR.jpg', 'P244_1_FLIR.jpg', 'P245_1_FLIR.jpg', 'P245_2_FLIR.jpg', 'P246_1_FLIR.jpg', 'P246_2_FLIR.jpg', 'P247_1_FLIR.jpg', 'P247_2_FLIR.jpg', 'P248_1_FLIR.jpg', 'P249_1_FLIR.jpg', 'P249_2_FLIR.jpg', 'P250_1_FLIR.jpg', 'P250_2_FLIR.jpg', 'P251_1_FLIR.jpg', 'P251_2_FLIR.jpg', 'P252_1_FLIR.jpg', 'P253_1_FLIR.jpg', 'P253_2_FLIR.jpg', 'P254_1_FLIR.jpg', 'P254_2_FLIR.jpg', 'P255_1_FLIR.jpg', 'P255_2_FLIR.jpg', 'P256_1_FLIR.jpg', 'P256_2_FLIR.jpg', 'P257_1_FLIR.jpg', 'P257_2_FLIR.jpg', 'P258_1_FLIR.jpg', 'P258_2_FLIR.jpg', 'P259_2_FLIR.jpg', 'P260_2_FLIR.jpg', 'P261_1_FLIR.jpg', 'P261_2_FLIR.jpg', 'P262_1_FLIR.jpg', 'P262_2_FLIR.jpg', 'P263_1_FLIR.jpg', 'P263_2_FLIR.jpg', 'P264_1_FLIR.jpg', 'P264_2_FLIR.jpg', 'P265_1_FLIR.jpg', 'P265_2_FLIR.jpg', 'P266_1_FLIR.jpg', 'P266_2_FLIR.jpg', 'P267_1_FLIR.jpg', 'P267_2_FLIR.jpg', 'P268_1_FLIR.jpg', 'P268_2_FLIR.jpg', 'P269_1_FLIR.jpg', 'P269_2_FLIR.jpg', 'P270_1_FLIR.jpg', 'P270_2_FLIR.jpg', 'P271_1_FLIR.jpg', 'P271_2_FLIR.jpg', 'P272_1_FLIR.jpg', 'P272_2_FLIR.jpg', 'P273_1_FLIR.jpg', 'P273_2_FLIR.jpg', 'P274_1_FLIR.jpg', 'P274_2_FLIR.jpg', 'P275_1_FLIR.jpg', 'P275_2_FLIR.jpg', 'P276_1_FLIR.jpg', 'P277_1_FLIR.jpg', 'P277_2_FLIR.jpg', 'P278_1_FLIR.jpg', 'P278_2_FLIR.jpg', 'P279_1_FLIR.jpg', 'P279_2_FLIR.jpg', 'P281_1_FLIR.jpg', 'P281_2_FLIR.jpg', 'P282_1_FLIR.jpg', 'P282_2_FLIR.jpg', 'P283_1_FLIR.jpg', 'P284_1_FLIR.jpg', 'P285_1_FLIR.jpg', 'P286_1_FLIR.jpg']

In [69]:
import os
import shutil

input_dir = img_thermal
output_dir = img_root

os.makedirs(output_dir, exist_ok=True)

for i, fname in enumerate(sorted(os.listdir(input_dir))):
    if not fname.lower().endswith("thermal.jpg"):
        continue
    

    ext = os.path.splitext(fname)[1]
    name = os.path.splitext(fname)[0][1:4]# .jpg
    name_index=os.path.splitext(fname)[0][5]
    num = int(name)
    if(num >= 254):
        new_name = f"P{name}_{name_index}_FLIR.jpg"
        src = os.path.join(input_dir, fname)
        dst = os.path.join(output_dir, new_name)
        shutil.copy2(src, dst)  # copy + 保留 metadata

In [77]:
from ultralytics import YOLO
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

# YOLOv8-seg
model = YOLO("yolov8n-seg.pt")

def GetRoughtOutlineYolo(img_path,output_path = "thermal_contour_only.jpg"):
    results = model(img_path)
    if results[0].masks is not None:
        masks = results[0].masks.data.cpu().numpy()
        orig_img = cv2.imread(img_path)
        h, w = orig_img.shape[:2]
        if masks is not None and len(masks) > 0:
        
            contour_canvas = np.zeros((h, w, 3), dtype=np.uint8)

            for i, mask in enumerate(masks):
                # resize 
                mask = cv2.resize(mask, (w, h))
                mask = (mask > 0.5).astype(np.uint8) * 255  
                contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
                cv2.drawContours(contour_canvas, contours, -1, (255, 255, 255), 2) 

            cv2.imwrite(output_path, contour_canvas)
    else:
        print('fail: ', img_path)

In [82]:
def GetRoughtOutlineYoloThermal(img_path,output_path = "thermal_contour_only.jpg"):
    conf = 0.05
    results = model(img_path, conf=conf)
   

    orig_img = cv2.imread(img_path)
    h, w = orig_img.shape[:2]


    if results[0].masks is not None:
        masks = results[0].masks.data.cpu().numpy()
        contour_canvas = np.zeros((h, w, 3), dtype=np.uint8)

        for i, mask in enumerate(masks):
            
            mask = cv2.resize(mask, (w, h))
            mask = (mask > 0.5).astype(np.uint8) * 255

            
            contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            cv2.drawContours(contour_canvas, contours, -1, (255, 255, 255), 2)

        cv2.imwrite(output_path, contour_canvas)

In [ ]:
image_path = r"D:\\BODYPAR\\Graphonomy\\Graphonomy-master\\img\\P010_2_FLIR.jpg"
outline_flir = r"D:\\BODYPAR\\Graphonomy\\Graphonomy-master\\tempboundary\\P010_2_contour.jpg"
GetRoughtOutlineYolo(img_path=image_path,output_path=outline_flir)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P010_2_FLIR.jpg: 480x640 1 person, 1 chair, 52.2ms
Speed: 3.8ms preprocess, 52.2ms inference, 3.9ms postprocess per image at shape (1, 3, 480, 640)

In [ ]:
img_matched = "D:\BODYPAR\Graphonomy\Graphonomy-master\img_matched"
img_output = "D:\BODYPAR\Graphonomy\Graphonomy-master\img_output_new"

In [11]:
def get_largest_component(mask):
    cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not cnts:
        return mask
    cnt = max(cnts, key=cv2.contourArea)
    largest = np.zeros_like(mask)
    cv2.drawContours(largest, [cnt], -1, 255, thickness=-1)  
    return largest

def multi_scale_template_match(thermal_path, flir_path, scales=None, out_path="match_result.png"):
    
    thermal = cv2.imread(thermal_path, cv2.IMREAD_GRAYSCALE)
    flir = cv2.imread(flir_path, cv2.IMREAD_GRAYSCALE)

    
    _, thermal = cv2.threshold(thermal, 10, 255, cv2.THRESH_BINARY)
    _, flir = cv2.threshold(flir, 10, 255, cv2.THRESH_BINARY)

    #thermal = get_largest_component(thermal)
    #flir = get_largest_component(flir)

    if scales is None:
        scales = np.linspace(0.5, 1.5, 11)  #  [0.5x ~ 1.5x]

    best_val = -1
    best_scale = None
    best_loc = None
    best_template = None

    
    for s in scales:
        new_w = int(thermal.shape[1] * s)
        new_h = int(thermal.shape[0] * s)
        if new_w < 10 or new_h < 10: 
            continue

        template = cv2.resize(thermal, (new_w, new_h))
        res = cv2.matchTemplate(flir, template, cv2.TM_CCOEFF_NORMED)
        min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(res)

        if max_val > best_val:
            best_val = max_val
            best_scale = s
            best_loc = max_loc
            best_template = template.copy()

    
    top_left = best_loc
    h, w = best_template.shape
    bottom_right = (top_left[0] + w, top_left[1] + h)

    flir_bgr = cv2.cvtColor(flir, cv2.COLOR_GRAY2BGR)
    cv2.rectangle(flir_bgr, top_left, bottom_right, (0,0,255), 2)  

    cv2.imwrite(out_path, flir_bgr)
    print(f"[OK] scale={best_scale:.2f}, score={best_val:.3f}, loc = {best_loc},{out_path}")

    return best_scale, best_val, best_loc

In [98]:
def ReduceOutline(img_path,output_path):
    img = cv2.imread(img_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    mask = np.where(gray > 0, 255, 0).astype(np.uint8)

    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cnt = max(contours, key=cv2.contourArea)

    out = np.zeros_like(img)
    cv2.drawContours(out, [cnt], -1, (0,255,0), 2)  

    cv2.imwrite(output_path, out)

In [ ]:
scale, score, loc = multi_scale_template_match(
    "D:\\BODYPAR\\Graphonomy\\Graphonomy-master\\tempboundary\\P010_2_thermal_contour.jpg",
    "D:\\BODYPAR\\Graphonomy\\Graphonomy-master\\tempboundary\\P010_2_contour_fix.jpg",
    scales=np.linspace(0.3, 2.0, 20)  
)

[OK] scale=1.55, score=0.255, loc = (70, 47),match_result.png

In [12]:
data_scale = []

for file in jpg_files:
    file_name = file[:-9]
    thermal_outline = f"D:\\BODYPAR\\Graphonomy\\Graphonomy-master\\tempboundary\\{file_name}_thermal_contour.jpg"
    flir_outline = f"D:\\BODYPAR\\Graphonomy\\Graphonomy-master\\tempboundary\\{file_name}_contour_fix.jpg"
    output_name = f"D:\\BODYPAR\\Graphonomy\\Graphonomy-master\\imgtemp\\{file_name}_macthed.jpg"
    
    scale, score, loc = multi_scale_template_match(
        thermal_path=thermal_outline,
        flir_path=flir_outline,
        out_path=output_name,
        scales=np.linspace(0.3, 2.0, 20)  
    )
    data_scaled = {'img_name' : file_name, 'scale' : scale,'score': score,'loc': loc}
    data_scale.append(data_scaled)

data_scale_df = pd.DataFrame(data_scale)
data_scale_df.head()

[OK] scale=1.55, score=0.415, loc = (71, 46),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P010_1_macthed.jpg
[OK] scale=1.55, score=0.255, loc = (70, 47),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P010_2_macthed.jpg
[OK] scale=0.30, score=0.226, loc = (305, 315),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P011_1_macthed.jpg
[OK] scale=0.30, score=0.245, loc = (399, 359),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P011_2_macthed.jpg
[OK] scale=0.30, score=0.244, loc = (361, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P012_1_macthed.jpg
[OK] scale=0.30, score=0.299, loc = (226, 328),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P012_2_macthed.jpg
[OK] scale=1.55, score=0.260, loc = (71, 48),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P013_1_macthed.jpg
[OK] scale=1.64, score=0.291, loc = (49, 52),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P013_2_macthed.jpg
[OK] scale=0.30, score=0.278, loc = (336, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P014_1_macthed.jpg
[OK] scale=0.30, score=0.238, loc = (135, 343),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P015_1_macthed.jpg
[OK] scale=1.46, score=0.282, loc = (83, 64),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P015_2_macthed.jpg
[OK] scale=0.48, score=0.217, loc = (225, 317),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P016_1_macthed.jpg
[OK] scale=0.30, score=0.358, loc = (287, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P017_1_macthed.jpg
[OK] scale=1.46, score=0.245, loc = (87, 54),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P017_2_macthed.jpg
[OK] scale=0.30, score=0.280, loc = (318, 116),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P018_1_macthed.jpg
[OK] scale=1.55, score=0.176, loc = (71, 44),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P018_2_macthed.jpg
[OK] scale=1.55, score=0.322, loc = (71, 45),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P019_1_macthed.jpg
[OK] scale=1.64, score=0.303, loc = (47, 53),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P019_2_macthed.jpg
[OK] scale=1.55, score=0.245, loc = (71, 49),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P020_1_macthed.jpg
[OK] scale=1.55, score=0.283, loc = (65, 58),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P020_2_macthed.jpg
[OK] scale=0.48, score=0.218, loc = (98, 269),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P021_1_macthed.jpg
[OK] scale=0.30, score=0.276, loc = (274, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P021_2_macthed.jpg
[OK] scale=0.30, score=0.246, loc = (339, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P022_1_macthed.jpg
[OK] scale=1.55, score=0.317, loc = (72, 45),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P022_2_macthed.jpg
[OK] scale=0.39, score=0.395, loc = (325, 386),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P023_1_macthed.jpg
[OK] scale=1.55, score=0.306, loc = (72, 44),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P023_2_macthed.jpg
[OK] scale=0.30, score=0.248, loc = (276, 1),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P024_1_macthed.jpg
[OK] scale=1.55, score=0.300, loc = (65, 56),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P024_2_macthed.jpg
[OK] scale=0.30, score=0.203, loc = (354, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P025_1_macthed.jpg
[OK] scale=1.55, score=0.425, loc = (71, 44),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P025_2_macthed.jpg
[OK] scale=1.55, score=0.237, loc = (66, 60),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P026_1_macthed.jpg
[OK] scale=1.55, score=0.350, loc = (72, 43),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P026_2_macthed.jpg
[OK] scale=0.30, score=0.191, loc = (319, 177),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P027_1_macthed.jpg
[OK] scale=1.55, score=0.235, loc = (72, 45),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P027_2_macthed.jpg
[OK] scale=1.55, score=0.390, loc = (71, 45),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P028_1_macthed.jpg
[OK] scale=1.55, score=0.331, loc = (65, 57),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P028_2_macthed.jpg
[OK] scale=0.39, score=0.304, loc = (166, 192),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P029_1_macthed.jpg
[OK] scale=0.48, score=0.256, loc = (314, 20),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P029_2_macthed.jpg
[OK] scale=0.30, score=0.253, loc = (326, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P030_1_macthed.jpg
[OK] scale=0.30, score=0.197, loc = (238, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P031_1_macthed.jpg
[OK] scale=1.55, score=0.191, loc = (65, 56),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P031_2_macthed.jpg
[OK] scale=0.39, score=0.300, loc = (292, 386),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P032_1_macthed.jpg
[OK] scale=0.30, score=0.199, loc = (325, 343),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P032_2_macthed.jpg
[OK] scale=0.30, score=0.345, loc = (331, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P033_1_macthed.jpg
[OK] scale=0.30, score=0.231, loc = (213, 408),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P033_2_macthed.jpg
[OK] scale=1.55, score=0.236, loc = (70, 43),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P034_1_macthed.jpg
[OK] scale=1.55, score=0.301, loc = (69, 48),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P034_2_macthed.jpg
[OK] scale=1.55, score=0.218, loc = (70, 62),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P036_1_macthed.jpg
[OK] scale=0.30, score=0.231, loc = (142, 292),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P036_2_macthed.jpg
[OK] scale=0.30, score=0.291, loc = (243, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P037_1_macthed.jpg
[OK] scale=1.46, score=0.163, loc = (90, 55),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P037_2_macthed.jpg
[OK] scale=0.30, score=0.342, loc = (266, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P038_1_macthed.jpg
[OK] scale=1.46, score=0.300, loc = (93, 52),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P038_2_macthed.jpg
[OK] scale=1.55, score=0.302, loc = (71, 48),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P039_1_macthed.jpg
[OK] scale=1.55, score=0.379, loc = (68, 58),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P039_2_macthed.jpg
[OK] scale=1.55, score=0.257, loc = (69, 59),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P040_1_macthed.jpg
[OK] scale=1.55, score=0.276, loc = (70, 47),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P040_2_macthed.jpg
[OK] scale=0.30, score=0.214, loc = (225, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P041_1_macthed.jpg
[OK] scale=1.55, score=0.207, loc = (62, 59),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P041_2_macthed.jpg
[OK] scale=1.55, score=0.289, loc = (64, 58),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P042_1_macthed.jpg
[OK] scale=1.55, score=0.218, loc = (71, 47),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P042_2_macthed.jpg
[OK] scale=0.30, score=0.236, loc = (162, 183),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P043_1_macthed.jpg
[OK] scale=1.55, score=0.399, loc = (70, 46),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P043_2_macthed.jpg
[OK] scale=1.55, score=0.330, loc = (71, 47),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P044_1_macthed.jpg
[OK] scale=0.30, score=0.252, loc = (162, 275),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P044_2_macthed.jpg
[OK] scale=0.39, score=0.335, loc = (201, 386),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P045_1_macthed.jpg
[OK] scale=0.30, score=0.256, loc = (291, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P045_2_macthed.jpg
[OK] scale=0.30, score=0.275, loc = (351, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P046_1_macthed.jpg
[OK] scale=0.39, score=0.282, loc = (144, 19),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P046_2_macthed.jpg
[OK] scale=0.30, score=0.245, loc = (317, 163),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P047_1_macthed.jpg
[OK] scale=1.55, score=0.531, loc = (71, 48),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P047_2_macthed.jpg
[OK] scale=1.55, score=0.325, loc = (71, 47),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P048_1_macthed.jpg
[OK] scale=0.84, score=0.270, loc = (122, 280),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P049_1_macthed.jpg
[OK] scale=1.55, score=0.503, loc = (70, 44),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P049_2_macthed.jpg
[OK] scale=1.55, score=0.270, loc = (70, 46),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P050_1_macthed.jpg
[OK] scale=1.55, score=0.338, loc = (71, 47),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P050_2_macthed.jpg
[OK] scale=0.30, score=0.249, loc = (322, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P051_1_macthed.jpg
[OK] scale=1.55, score=0.190, loc = (71, 47),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P051_2_macthed.jpg
[OK] scale=1.55, score=0.242, loc = (71, 49),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P052_1_macthed.jpg
[OK] scale=0.30, score=0.182, loc = (388, 211),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P052_2_macthed.jpg
[OK] scale=1.55, score=0.251, loc = (73, 45),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P053_1_macthed.jpg
[OK] scale=0.30, score=0.180, loc = (285, 392),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P053_2_macthed.jpg
[OK] scale=0.30, score=0.236, loc = (199, 408),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P054_1_macthed.jpg
[OK] scale=0.30, score=0.238, loc = (305, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P055_1_macthed.jpg
[OK] scale=0.30, score=0.241, loc = (327, 115),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P055_2_macthed.jpg
[OK] scale=0.39, score=0.297, loc = (229, 386),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P056_1_macthed.jpg
[OK] scale=1.55, score=0.295, loc = (67, 62),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P056_2_macthed.jpg
[OK] scale=1.55, score=0.300, loc = (71, 44),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P057_1_macthed.jpg
[OK] scale=1.55, score=0.272, loc = (72, 45),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P058_1_macthed.jpg
[OK] scale=1.55, score=0.222, loc = (71, 49),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P059_1_macthed.jpg
[OK] scale=1.55, score=0.296, loc = (70, 47),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P059_2_macthed.jpg
[OK] scale=0.30, score=0.227, loc = (229, 383),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P060_1_macthed.jpg
[OK] scale=0.30, score=0.237, loc = (204, 364),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P060_2_macthed.jpg
[OK] scale=0.30, score=0.297, loc = (251, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P061_1_macthed.jpg
[OK] scale=1.55, score=0.433, loc = (71, 45),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P061_2_macthed.jpg
[OK] scale=0.30, score=0.241, loc = (339, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P062_1_macthed.jpg
[OK] scale=1.55, score=0.238, loc = (72, 44),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P062_2_macthed.jpg
[OK] scale=1.55, score=0.362, loc = (73, 48),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P063_1_macthed.jpg
[OK] scale=1.55, score=0.195, loc = (70, 49),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P063_2_macthed.jpg
[OK] scale=0.30, score=0.278, loc = (321, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P064_1_macthed.jpg
[OK] scale=0.30, score=0.192, loc = (393, 330),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P064_2_macthed.jpg
[OK] scale=0.39, score=0.251, loc = (316, 386),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P065_1_macthed.jpg
[OK] scale=0.39, score=0.213, loc = (249, 203),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P065_2_macthed.jpg
[OK] scale=0.39, score=0.287, loc = (213, 386),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P066_1_macthed.jpg
[OK] scale=1.55, score=0.277, loc = (72, 47),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P066_2_macthed.jpg
[OK] scale=0.30, score=0.245, loc = (223, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P067_1_macthed.jpg
[OK] scale=1.64, score=0.295, loc = (50, 52),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P067_2_macthed.jpg
[OK] scale=0.30, score=0.300, loc = (415, 376),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P069_1_macthed.jpg
[OK] scale=0.48, score=0.194, loc = (171, 191),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P070_1_macthed.jpg
[OK] scale=1.55, score=0.294, loc = (71, 50),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P071_1_macthed.jpg
[OK] scale=1.55, score=0.321, loc = (69, 48),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P071_2_macthed.jpg
[OK] scale=1.55, score=0.383, loc = (70, 47),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P072_1_macthed.jpg
[OK] scale=1.55, score=0.295, loc = (71, 48),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P072_2_macthed.jpg
[OK] scale=0.30, score=0.276, loc = (247, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P073_1_macthed.jpg
[OK] scale=0.30, score=0.228, loc = (315, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P073_2_macthed.jpg
[OK] scale=0.30, score=0.353, loc = (229, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P074_1_macthed.jpg
[OK] scale=1.55, score=0.207, loc = (78, 46),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P074_2_macthed.jpg
[OK] scale=0.30, score=0.251, loc = (222, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P075_1_macthed.jpg
[OK] scale=1.55, score=0.251, loc = (71, 44),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P075_2_macthed.jpg
[OK] scale=1.55, score=0.198, loc = (67, 61),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P076_1_macthed.jpg
[OK] scale=1.64, score=0.245, loc = (48, 53),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P076_2_macthed.jpg
[OK] scale=0.30, score=0.228, loc = (203, 179),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P077_1_macthed.jpg
[OK] scale=0.39, score=0.229, loc = (132, 370),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P077_2_macthed.jpg
[OK] scale=1.55, score=0.377, loc = (70, 46),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P078_1_macthed.jpg
[OK] scale=1.55, score=0.307, loc = (71, 46),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P078_2_macthed.jpg
[OK] scale=0.30, score=0.226, loc = (216, 277),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P079_1_macthed.jpg
[OK] scale=0.30, score=0.274, loc = (179, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P080_1_macthed.jpg
[OK] scale=0.30, score=0.225, loc = (385, 333),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P080_2_macthed.jpg
[OK] scale=0.30, score=0.204, loc = (138, 408),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P081_1_macthed.jpg
[OK] scale=0.39, score=0.212, loc = (159, 195),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P081_2_macthed.jpg
[OK] scale=0.30, score=0.226, loc = (215, 343),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P082_1_macthed.jpg
[OK] scale=0.39, score=0.405, loc = (198, 386),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P083_1_macthed.jpg
[OK] scale=0.66, score=0.182, loc = (147, 140),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P083_2_macthed.jpg
[OK] scale=1.55, score=0.375, loc = (71, 45),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P084_1_macthed.jpg
[OK] scale=0.30, score=0.288, loc = (130, 355),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P084_2_macthed.jpg
[OK] scale=1.55, score=0.270, loc = (71, 48),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P085_1_macthed.jpg
[OK] scale=0.30, score=0.209, loc = (191, 292),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P085_2_macthed.jpg
[OK] scale=0.30, score=0.216, loc = (174, 408),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P086_1_macthed.jpg
[OK] scale=0.30, score=0.255, loc = (254, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P086_2_macthed.jpg
[OK] scale=0.30, score=0.329, loc = (298, 320),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P087_1_macthed.jpg
[OK] scale=1.55, score=0.303, loc = (70, 45),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P087_2_macthed.jpg
[OK] scale=0.30, score=0.213, loc = (243, 408),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P088_1_macthed.jpg
[OK] scale=1.55, score=0.395, loc = (82, 43),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P088_2_macthed.jpg
[OK] scale=0.30, score=0.230, loc = (204, 16),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P089_1_macthed.jpg
[OK] scale=0.30, score=0.194, loc = (433, 370),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P090_1_macthed.jpg
[OK] scale=1.55, score=0.307, loc = (72, 44),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P090_2_macthed.jpg
[OK] scale=1.55, score=0.275, loc = (70, 46),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P091_1_macthed.jpg
[OK] scale=0.39, score=0.193, loc = (323, 73),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P091_2_macthed.jpg
[OK] scale=1.55, score=0.282, loc = (70, 46),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P092_1_macthed.jpg
[OK] scale=1.55, score=0.273, loc = (70, 44),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P092_2_macthed.jpg
[OK] scale=1.55, score=0.294, loc = (71, 44),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P093_1_macthed.jpg
[OK] scale=0.30, score=0.210, loc = (200, 177),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P093_2_macthed.jpg
[OK] scale=1.55, score=0.249, loc = (70, 45),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P094_1_macthed.jpg
[OK] scale=1.55, score=0.241, loc = (72, 48),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P094_2_macthed.jpg
[OK] scale=0.30, score=0.240, loc = (441, 198),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P095_1_macthed.jpg
[OK] scale=1.55, score=0.342, loc = (71, 46),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P095_2_macthed.jpg
[OK] scale=1.55, score=0.375, loc = (73, 47),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P096_1_macthed.jpg
[OK] scale=0.30, score=0.206, loc = (320, 306),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P096_2_macthed.jpg
[OK] scale=1.64, score=0.266, loc = (50, 56),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P097_1_macthed.jpg
[OK] scale=0.39, score=0.358, loc = (302, 386),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P098_1_macthed.jpg
[OK] scale=1.55, score=0.255, loc = (71, 43),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P098_2_macthed.jpg
[OK] scale=0.30, score=0.190, loc = (436, 338),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P099_1_macthed.jpg
[OK] scale=1.55, score=0.248, loc = (71, 46),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P099_2_macthed.jpg
[OK] scale=0.39, score=0.238, loc = (284, 40),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P100_1_macthed.jpg
[OK] scale=0.30, score=0.222, loc = (312, 354),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P100_2_macthed.jpg
[OK] scale=0.30, score=0.251, loc = (226, 96),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P101_1_macthed.jpg
[OK] scale=0.30, score=0.238, loc = (124, 165),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P101_2_macthed.jpg
[OK] scale=0.30, score=0.293, loc = (180, 407),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P103_1_macthed.jpg
[OK] scale=1.55, score=0.302, loc = (72, 43),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P103_2_macthed.jpg
[OK] scale=0.30, score=0.229, loc = (278, 356),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P105_1_macthed.jpg
[OK] scale=0.39, score=0.307, loc = (96, 293),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P105_2_macthed.jpg
[OK] scale=1.55, score=0.299, loc = (71, 45),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P106_1_macthed.jpg
[OK] scale=0.48, score=0.256, loc = (232, 45),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P106_2_macthed.jpg
[OK] scale=0.39, score=0.232, loc = (221, 387),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P107_1_macthed.jpg
[OK] scale=1.55, score=0.327, loc = (66, 45),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P107_2_macthed.jpg
[OK] scale=0.39, score=0.360, loc = (254, 386),D:\BODYPAR\Graphonomy\Graphonomy-master\imgtemp\P108_1_macthed.jpg

  img_name     scale     score         loc
0   P010_1  1.552632  0.414863    (71, 46)
1   P010_2  1.552632  0.254960    (70, 47)
2   P011_1  0.300000  0.225691  (305, 315)
3   P011_2  0.300000  0.245246  (399, 359)
4   P012_1  0.300000  0.243514  (361, 407)

In [13]:
fal_df = data_scale_df[data_scale_df['scale'] < 1]
fal_df

    img_name     scale     score         loc
2     P011_1  0.300000  0.225691  (305, 315)
3     P011_2  0.300000  0.245246  (399, 359)
4     P012_1  0.300000  0.243514  (361, 407)
5     P012_2  0.300000  0.298977  (226, 328)
8     P014_1  0.300000  0.278452  (336, 407)
..       ...       ...       ...         ...
478   P281_2  0.300000  0.176467  (307, 355)
479   P282_1  0.300000  0.253501  (343, 289)
480   P282_2  0.389474  0.222151  (262, 302)
481   P283_1  0.300000  0.191086  (357, 252)
484   P286_1  0.300000  0.246022  (389, 190)

[248 rows x 4 columns]

In [129]:
from ultralytics import YOLO


model = YOLO("yolov8n-seg.pt")

def GetYOLOBox(img_path,output_path):
    results = model(img_path)

    results[0].save(output_path)
    result = results[0]
    boxes = result.boxes.xyxy.cpu().numpy()   
    confs = result.boxes.conf.cpu().numpy()   
    clss  = result.boxes.cls.cpu().numpy()    

    for (box, conf, cls) in zip(boxes, confs, clss):
        if(cls == 0):
            x1, y1, x2, y2 = map(int, box)
            w, h = x2 - x1, y2 - y1
            return x1,y1,w,h
        
    print(f" {img_path} No People Detection")
    return None

In [ ]:
output_box = r"D:\\BODYPAR\\Graphonomy\\Graphonomy-master\\imgtemp\\failed"
erro_matched_files = fal_df['img_name'].unique().tolist()
for file in erro_matched_files:
    file_name = file
    thermal_img = img_thermal + f'\{file_name}_thermal.jpg'
    flir_img = img_root + f'\{file_name}_FLIR.jpg'
    thermal_box = output_box  + f'\{file_name}_thermal_box.jpg'
    flir_box = output_box  + f'\{file_name}_FLIR_box.jpg'
    
    box_thermal = GetYOLOBox(thermal_img,thermal_box)
    box =  GetYOLOBox(flir_img,flir_box)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P011_1_thermal.jpg: 480x640 1 person, 1 traffic light, 1 vase, 52.1ms
Speed: 3.8ms preprocess, 52.1ms inference, 5.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P011_1_FLIR.jpg: 480x640 1 person, 52.3ms
Speed: 3.6ms preprocess, 52.3ms inference, 3.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P011_2_thermal.jpg: 480x640 1 person, 46.6ms
Speed: 3.9ms preprocess, 46.6ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P011_2_FLIR.jpg: 480x640 1 person, 45.2ms
Speed: 3.3ms preprocess, 45.2ms inference, 4.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P012_1_thermal.jpg: 480x640 1 tv, 1 vase, 45.4ms
Speed: 3.6ms preprocess, 45.4ms inference, 3.7ms postprocess per image at shape (1, 3, 480, 640)
 D:/BODYPAR/Graphonomy/Graphonomy-master/img_thermal\P012_1_thermal.jpg No People Detection

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P012_1_FLIR.jpg: 480x640 1 person, 1 boat, 8.5ms
Speed: 0.8ms preprocess, 8.5ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P012_2_thermal.jpg: 480x640 1 person, 9.8ms
Speed: 1.2ms preprocess, 9.8ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P012_2_FLIR.jpg: 480x640 1 person, 9.2ms
Speed: 1.0ms preprocess, 9.2ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P014_1_thermal.jpg: 480x640 1 person, 1 traffic light, 9.6ms
Speed: 1.6ms preprocess, 9.6ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P014_1_FLIR.jpg: 480x640 2 persons, 1 backpack, 9.2ms
Speed: 1.1ms preprocess, 9.2ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P015_1_thermal.jpg: 480x640 1 person, 1 boat, 10.2ms
Speed: 1.7ms preprocess, 10.2ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P015_1_FLIR.jpg: 480x640 1 person, 8.8ms
Speed: 0.9ms preprocess, 8.8ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P016_1_thermal.jpg: 480x640 1 person, 1 vase, 13.2ms
Speed: 1.4ms preprocess, 13.2ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P016_1_FLIR.jpg: 480x640 3 persons, 3 chairs, 1 dining table, 7.8ms
Speed: 0.8ms preprocess, 7.8ms inference, 3.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P017_1_thermal.jpg: 480x640 1 person, 1 cell phone, 9.0ms
Speed: 1.4ms preprocess, 9.0ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P017_1_FLIR.jpg: 480x640 2 persons, 1 car, 1 parking meter, 2 chairs, 9.0ms
Speed: 1.0ms preprocess, 9.0ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P018_1_thermal.jpg: 480x640 1 person, 1 cell phone, 7.8ms
Speed: 1.2ms preprocess, 7.8ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P018_1_FLIR.jpg: 480x640 2 persons, 2 bicycles, 11.5ms
Speed: 0.9ms preprocess, 11.5ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P021_1_thermal.jpg: 480x640 1 person, 10.6ms
Speed: 1.4ms preprocess, 10.6ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P021_1_FLIR.jpg: 480x640 1 person, 1 boat, 1 bench, 9.3ms
Speed: 1.0ms preprocess, 9.3ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P021_2_thermal.jpg: 480x640 1 person, 1 traffic light, 9.2ms
Speed: 1.2ms preprocess, 9.2ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P021_2_FLIR.jpg: 480x640 3 persons, 8.8ms
Speed: 1.0ms preprocess, 8.8ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P022_1_thermal.jpg: 480x640 1 person, 9.3ms
Speed: 1.4ms preprocess, 9.3ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P022_1_FLIR.jpg: 480x640 1 person, 1 boat, 9.4ms
Speed: 0.8ms preprocess, 9.4ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P023_1_thermal.jpg: 480x640 1 person, 9.6ms
Speed: 1.4ms preprocess, 9.6ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P023_1_FLIR.jpg: 480x640 1 person, 1 boat, 1 bench, 8.1ms
Speed: 0.9ms preprocess, 8.1ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P024_1_thermal.jpg: 480x640 1 person, 8.5ms
Speed: 1.2ms preprocess, 8.5ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P024_1_FLIR.jpg: 480x640 3 persons, 11.6ms
Speed: 1.0ms preprocess, 11.6ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P025_1_thermal.jpg: 480x640 1 person, 1 cell phone, 1 vase, 11.1ms
Speed: 1.6ms preprocess, 11.1ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P025_1_FLIR.jpg: 480x640 1 person, 1 car, 1 truck, 1 bench, 8.7ms
Speed: 1.1ms preprocess, 8.7ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P027_1_thermal.jpg: 480x640 1 person, 1 traffic light, 9.2ms
Speed: 2.0ms preprocess, 9.2ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P027_1_FLIR.jpg: 480x640 7 persons, 2 cars, 2 benchs, 8.5ms
Speed: 0.9ms preprocess, 8.5ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P029_1_thermal.jpg: 480x640 1 person, 8.5ms
Speed: 1.5ms preprocess, 8.5ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P029_1_FLIR.jpg: 480x640 1 person, 2 benchs, 1 handbag, 11.2ms
Speed: 0.9ms preprocess, 11.2ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P029_2_thermal.jpg: 480x640 1 person, 1 traffic light, 9.0ms
Speed: 1.1ms preprocess, 9.0ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P029_2_FLIR.jpg: 480x640 1 person, 9.7ms
Speed: 0.9ms preprocess, 9.7ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P030_1_thermal.jpg: 480x640 1 person, 1 suitcase, 12.3ms
Speed: 1.6ms preprocess, 12.3ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P030_1_FLIR.jpg: 480x640 1 person, 3 bicycles, 8.6ms
Speed: 0.8ms preprocess, 8.6ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P031_1_thermal.jpg: 480x640 1 person, 16.4ms
Speed: 1.3ms preprocess, 16.4ms inference, 4.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P031_1_FLIR.jpg: 480x640 2 persons, 8.5ms
Speed: 0.9ms preprocess, 8.5ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P032_1_thermal.jpg: 480x640 1 person, 9.8ms
Speed: 1.5ms preprocess, 9.8ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P032_1_FLIR.jpg: 480x640 2 persons, 2 cars, 1 motorcycle, 11.3ms
Speed: 1.2ms preprocess, 11.3ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P032_2_thermal.jpg: 480x640 1 person, 12.2ms
Speed: 1.6ms preprocess, 12.2ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P032_2_FLIR.jpg: 480x640 1 person, 1 boat, 12.1ms
Speed: 1.2ms preprocess, 12.1ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P033_1_thermal.jpg: 480x640 1 fire hydrant, 1 cell phone, 10.7ms
Speed: 1.6ms preprocess, 10.7ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)
 D:/BODYPAR/Graphonomy/Graphonomy-master/img_thermal\P033_1_thermal.jpg No People Detection

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P033_1_FLIR.jpg: 480x640 1 person, 3 benchs, 12.9ms
Speed: 1.4ms preprocess, 12.9ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P033_2_thermal.jpg: 480x640 1 person, 1 vase, 13.7ms
Speed: 1.7ms preprocess, 13.7ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P033_2_FLIR.jpg: 480x640 1 person, 1 dining table, 11.7ms
Speed: 0.9ms preprocess, 11.7ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P036_2_thermal.jpg: 480x640 1 person, 10.6ms
Speed: 1.3ms preprocess, 10.6ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P036_2_FLIR.jpg: 480x640 1 person, 8.4ms
Speed: 1.0ms preprocess, 8.4ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P037_1_thermal.jpg: 480x640 1 person, 12.0ms
Speed: 1.3ms preprocess, 12.0ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P037_1_FLIR.jpg: 480x640 2 persons, 1 parking meter, 11.1ms
Speed: 0.8ms preprocess, 11.1ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P038_1_thermal.jpg: 480x640 1 person, 8.7ms
Speed: 1.3ms preprocess, 8.7ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P038_1_FLIR.jpg: 480x640 2 persons, 9.5ms
Speed: 0.9ms preprocess, 9.5ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P041_1_thermal.jpg: 480x640 1 person, 11.9ms
Speed: 1.8ms preprocess, 11.9ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P041_1_FLIR.jpg: 480x640 2 persons, 1 bench, 9.4ms
Speed: 1.0ms preprocess, 9.4ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P043_1_thermal.jpg: 480x640 2 persons, 11.4ms
Speed: 1.4ms preprocess, 11.4ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P043_1_FLIR.jpg: 480x640 1 person, 9.5ms
Speed: 0.9ms preprocess, 9.5ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P044_2_thermal.jpg: 480x640 1 person, 12.8ms
Speed: 1.4ms preprocess, 12.8ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P044_2_FLIR.jpg: 480x640 1 person, 1 boat, 1 backpack, 9.2ms
Speed: 0.9ms preprocess, 9.2ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P045_1_thermal.jpg: 480x640 1 person, 10.2ms
Speed: 2.2ms preprocess, 10.2ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P045_1_FLIR.jpg: 480x640 1 person, 3 cars, 9.2ms
Speed: 0.9ms preprocess, 9.2ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P045_2_thermal.jpg: 480x640 1 person, 9.6ms
Speed: 1.6ms preprocess, 9.6ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P045_2_FLIR.jpg: 480x640 1 person, 1 motorcycle, 9.5ms
Speed: 1.0ms preprocess, 9.5ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P046_1_thermal.jpg: 480x640 1 person, 15.7ms
Speed: 1.3ms preprocess, 15.7ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P046_1_FLIR.jpg: 480x640 2 persons, 1 bench, 9.1ms
Speed: 1.0ms preprocess, 9.1ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P046_2_thermal.jpg: 480x640 1 person, 9.8ms
Speed: 1.4ms preprocess, 9.8ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P046_2_FLIR.jpg: 480x640 1 person, 1 bicycle, 9.3ms
Speed: 1.0ms preprocess, 9.3ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P047_1_thermal.jpg: 480x640 1 person, 8.3ms
Speed: 1.2ms preprocess, 8.3ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P047_1_FLIR.jpg: 480x640 1 person, 1 bench, 9.4ms
Speed: 1.0ms preprocess, 9.4ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P049_1_thermal.jpg: 480x640 1 person, 1 traffic light, 8.4ms
Speed: 1.3ms preprocess, 8.4ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P049_1_FLIR.jpg: 480x640 1 person, 1 motorcycle, 11.1ms
Speed: 0.9ms preprocess, 11.1ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P051_1_thermal.jpg: 480x640 1 person, 15.0ms
Speed: 1.4ms preprocess, 15.0ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P051_1_FLIR.jpg: 480x640 1 person, 8.4ms
Speed: 0.9ms preprocess, 8.4ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P052_2_thermal.jpg: 480x640 1 person, 8.9ms
Speed: 1.2ms preprocess, 8.9ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P052_2_FLIR.jpg: 480x640 2 persons, 1 truck, 9.2ms
Speed: 1.0ms preprocess, 9.2ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P053_2_thermal.jpg: 480x640 1 person, 11.9ms
Speed: 1.3ms preprocess, 11.9ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P053_2_FLIR.jpg: 480x640 2 persons, 9.4ms
Speed: 1.0ms preprocess, 9.4ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P054_1_thermal.jpg: 480x640 1 person, 8.9ms
Speed: 1.6ms preprocess, 8.9ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P054_1_FLIR.jpg: 480x640 1 person, 1 chair, 8.8ms
Speed: 0.9ms preprocess, 8.8ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P055_1_thermal.jpg: 480x640 1 person, 10.0ms
Speed: 1.5ms preprocess, 10.0ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P055_1_FLIR.jpg: 480x640 1 person, 3 chairs, 10.1ms
Speed: 1.0ms preprocess, 10.1ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P055_2_thermal.jpg: 480x640 1 person, 9.2ms
Speed: 1.4ms preprocess, 9.2ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P055_2_FLIR.jpg: 480x640 1 person, 10.5ms
Speed: 1.1ms preprocess, 10.5ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P056_1_thermal.jpg: 480x640 1 person, 8.3ms
Speed: 1.2ms preprocess, 8.3ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P056_1_FLIR.jpg: 480x640 1 person, 1 train, 1 traffic light, 10.4ms
Speed: 1.0ms preprocess, 10.4ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P060_1_thermal.jpg: 480x640 1 person, 1 bottle, 9.2ms
Speed: 1.2ms preprocess, 9.2ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P060_1_FLIR.jpg: 480x640 5 persons, 2 benchs, 9.2ms
Speed: 1.0ms preprocess, 9.2ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P060_2_thermal.jpg: 480x640 1 cell phone, 9.9ms
Speed: 1.6ms preprocess, 9.9ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)
 D:/BODYPAR/Graphonomy/Graphonomy-master/img_thermal\P060_2_thermal.jpg No People Detection

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P060_2_FLIR.jpg: 480x640 1 person, 1 bench, 9.7ms
Speed: 0.8ms preprocess, 9.7ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P061_1_thermal.jpg: 480x640 1 person, 1 cell phone, 10.4ms
Speed: 1.2ms preprocess, 10.4ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P061_1_FLIR.jpg: 480x640 1 person, 8.8ms
Speed: 0.8ms preprocess, 8.8ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P062_1_thermal.jpg: 480x640 1 person, 1 cell phone, 8.4ms
Speed: 1.4ms preprocess, 8.4ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P062_1_FLIR.jpg: 480x640 1 person, 1 bicycle, 8.6ms
Speed: 0.9ms preprocess, 8.6ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P064_1_thermal.jpg: 480x640 1 person, 1 backpack, 14.4ms
Speed: 1.3ms preprocess, 14.4ms inference, 3.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 D:\BODYPAR\Graphonomy\Graphonomy-master\img\P064_1_FLIR.jpg: 480x640 1 person, 3 boats, 10.1ms

In [6]:
import cv2
import numpy as np

def ssim(img1, img2):

    C1 = (0.01 * 255) ** 2
    C2 = (0.03 * 255) ** 2

    img1 = img1.astype(np.float64)
    img2 = img2.astype(np.float64)

    mu1 = cv2.GaussianBlur(img1, (11, 11), 1.5)
    mu2 = cv2.GaussianBlur(img2, (11, 11), 1.5)

    mu1_sq = mu1 * mu1
    mu2_sq = mu2 * mu2
    mu1_mu2 = mu1 * mu2

    sigma1_sq = cv2.GaussianBlur(img1 * img1, (11, 11), 1.5) - mu1_sq
    sigma2_sq = cv2.GaussianBlur(img2 * img2, (11, 11), 1.5) - mu2_sq
    sigma12   = cv2.GaussianBlur(img1 * img2, (11, 11), 1.5) - mu1_mu2

    ssim_map = ((2 * mu1_mu2 + C1) * (2 * sigma12 + C2)) / \
               ((mu1_sq + mu2_sq + C1) * (sigma1_sq + sigma2_sq + C2))
    return ssim_map.mean()


def align_by_scale(img_orig, img_therm, scales=None, shift_range=10, step=2, vis_path="VI.jpg"):
    #if scales is None:
    scales = np.linspace(1.2, 1.7, 11)

    # GRAY
    g_therm = cv2.cvtColor(img_therm, cv2.COLOR_BGR2GRAY)
    h_t, w_t = g_therm.shape

    best_score, best_scale, best_aligned = -1, None, None

    for s in scales:
        # WHOLE PICTURE
        scaled = cv2.resize(img_orig, (int(img_orig.shape[1]/s), int(img_orig.shape[0]/s)))

       
        H, W = scaled.shape[:2]
        if H < h_t or W < w_t:
            continue  
        cx, cy = W // 2, H // 2
       # HIFT (dx, dy)
        for dy in range(-shift_range, shift_range+1, step):
            for dx in range(-shift_range, shift_range+1, step):
                x1 = cx - w_t//2 + dx
                y1 = cy - h_t//2 + dy
                x2, y2 = x1 + w_t, y1 + h_t

                if x1 < 0 or y1 < 0 or x2 > W or y2 > H:
                    continue

                roi_scaled = scaled[y1:y2, x1:x2]

                g_scaled = cv2.cvtColor(roi_scaled, cv2.COLOR_BGR2GRAY)
                score = ssim(g_therm, g_scaled)

                if score > best_score:
                    best_score = score
                    best_scale = s
                    best_shift = (dx, dy)
                    best_aligned = roi_scaled

    
    if vis_path and best_aligned is not None:
        overlay = cv2.addWeighted(best_aligned, 0.5, img_therm, 0.5, 0)
        concat = np.hstack((img_therm, best_aligned, overlay))
        cv2.imwrite(vis_path, concat)
       
    return best_aligned, best_scale, best_score, best_shift

In [ ]:
erro_matched_files = fal_df['img_name'].unique().tolist()
#erro_matched_files = ['P011_1']
align_data = []
for file in erro_matched_files:
    file_name = file
    thermal_img = img_thermal + f'\{file_name}_thermal.jpg'
    flir_img = img_root + f'\{file_name}_FLIR.jpg'
    img_orig = cv2.imread(flir_img)
    img_therm = cv2.imread(thermal_img)
    img_output = f'D:\\BODYPAR\\Graphonomy\\Graphonomy-master\\imgtemp\\{file_name}_matched1.jpg' 
    aligned, scale, score,best_shift = align_by_scale(
        img_orig, img_therm, 
        scales=[1.55263158, 1.64210526, 1.46315789, 1.37368421],
        vis_path = img_output
    )
    data_scaled = {'img_name' : file_name, 'scale' : scale,'score': score,'loc': best_shift}
    align_data.append(data_scaled)
    print(f"best_scale={scale:.2f}, best_score={score:.3f},best_shift = {best_shift}")

best_scale=1.55, best_score=0.176,best_shift = (-6, 4)
best_scale=1.50, best_score=0.162,best_shift = (6, -6)
best_scale=1.55, best_score=0.200,best_shift = (-6, 4)
best_scale=1.55, best_score=0.159,best_shift = (0, -4)
best_scale=1.55, best_score=0.156,best_shift = (0, -4)
best_scale=1.55, best_score=0.239,best_shift = (0, -4)
best_scale=1.55, best_score=0.186,best_shift = (0, -4)
best_scale=1.55, best_score=0.178,best_shift = (-8, 4)
best_scale=1.55, best_score=0.198,best_shift = (-6, 4)
best_scale=1.55, best_score=0.238,best_shift = (-2, -4)
best_scale=1.55, best_score=0.240,best_shift = (0, -4)
best_scale=1.55, best_score=0.160,best_shift = (-2, -4)
best_scale=1.55, best_score=0.140,best_shift = (-8, 4)
best_scale=1.55, best_score=0.138,best_shift = (-8, 4)
best_scale=1.55, best_score=0.216,best_shift = (-6, 4)
best_scale=1.60, best_score=0.218,best_shift = (-6, 4)
best_scale=1.55, best_score=0.159,best_shift = (-2, -4)
best_scale=1.50, best_score=0.177,best_shift = (6, -6)
best_scale=1.55, best_score=0.177,best_shift = (-2, -4)
best_scale=1.55, best_score=0.242,best_shift = (-2, -6)
best_scale=1.55, best_score=0.241,best_shift = (0, -6)
best_scale=1.55, best_score=0.185,best_shift = (-2, -6)
best_scale=1.20, best_score=0.060,best_shift = (8, -6)
best_scale=1.55, best_score=0.239,best_shift = (-6, 4)
best_scale=1.55, best_score=0.155,best_shift = (-8, 4)
best_scale=1.55, best_score=0.168,best_shift = (-8, 4)
best_scale=1.55, best_score=0.168,best_shift = (-2, -6)
best_scale=1.60, best_score=0.113,best_shift = (-6, 4)
best_scale=1.55, best_score=0.157,best_shift = (-2, -6)
best_scale=1.55, best_score=0.185,best_shift = (0, -4)
best_scale=1.55, best_score=0.180,best_shift = (0, -4)
best_scale=1.55, best_score=0.187,best_shift = (-2, -4)
best_scale=1.55, best_score=0.207,best_shift = (0, -4)
best_scale=1.55, best_score=0.122,best_shift = (-6, 4)
best_scale=1.55, best_score=0.119,best_shift = (-8, 4)
best_scale=1.55, best_score=0.158,best_shift = (-8, 4)
best_scale=1.55, best_score=0.202,best_shift = (-2, -4)
best_scale=1.55, best_score=0.234,best_shift = (6, -4)
best_scale=1.50, best_score=0.188,best_shift = (0, -6)
best_scale=1.50, best_score=0.188,best_shift = (0, -4)
best_scale=1.55, best_score=0.123,best_shift = (0, -6)
best_scale=1.55, best_score=0.188,best_shift = (-8, 4)
best_scale=1.55, best_score=0.156,best_shift = (0, -6)
best_scale=1.55, best_score=0.132,best_shift = (-2, -4)
best_scale=1.55, best_score=0.163,best_shift = (-6, 4)
best_scale=1.55, best_score=0.197,best_shift = (0, -4)
best_scale=1.55, best_score=0.146,best_shift = (-2, -6)
best_scale=1.55, best_score=0.189,best_shift = (-2, -4)
best_scale=1.55, best_score=0.231,best_shift = (-6, 4)
best_scale=1.55, best_score=0.148,best_shift = (0, -4)
best_scale=1.55, best_score=0.351,best_shift = (-6, 4)
best_scale=1.55, best_score=0.174,best_shift = (0, -4)
best_scale=1.55, best_score=0.212,best_shift = (0, -4)
best_scale=1.55, best_score=0.173,best_shift = (-6, 4)
best_scale=1.55, best_score=0.107,best_shift = (-8, 4)
best_scale=1.55, best_score=0.135,best_shift = (-8, 4)
best_scale=1.55, best_score=0.125,best_shift = (0, -4)
best_scale=1.55, best_score=0.195,best_shift = (-2, -4)
best_scale=1.55, best_score=0.174,best_shift = (-6, 4)
best_scale=1.55, best_score=0.250,best_shift = (0, -4)
best_scale=1.55, best_score=0.194,best_shift = (-8, 4)
best_scale=1.55, best_score=0.179,best_shift = (-6, 4)
best_scale=1.55, best_score=0.225,best_shift = (0, -4)
best_scale=1.55, best_score=0.166,best_shift = (-6, 4)
best_scale=1.55, best_score=0.148,best_shift = (-6, 4)
best_scale=1.55, best_score=0.173,best_shift = (-2, -4)
best_scale=1.60, best_score=0.232,best_shift = (-6, 4)
best_scale=1.55, best_score=0.175,best_shift = (0, -4)
best_scale=1.55, best_score=0.190,best_shift = (-8, 4)
best_scale=1.50, best_score=0.141,best_shift = (6, -6)
best_scale=1.55, best_score=0.211,best_shift = (0, -4)
best_scale=1.55, best_score=0.239,best_shift = (0, -4)
best_scale=1.55, best_score=0.164,best_shift = (-2, -4)
best_scale=1.55, best_score=0.188,best_shift = (-2, -4)
best_scale=1.55, best_score=0.220,best_shift = (0, -4)
best_scale=1.55, best_score=0.150,best_shift = (0, -4)
best_scale=1.55, best_score=0.196,best_shift = (0, -4)
best_scale=1.50, best_score=0.150,best_shift = (6, -6)
best_scale=1.55, best_score=0.161,best_shift = (-8, 4)
best_scale=1.55, best_score=0.257,best_shift = (-6, 4)
best_scale=1.55, best_score=0.101,best_shift = (-6, 6)
best_scale=1.55, best_score=0.171,best_shift = (0, -4)
best_scale=1.55, best_score=0.179,best_shift = (-8, 4)
best_scale=1.55, best_score=0.160,best_shift = (-6, 4)
best_scale=1.60, best_score=0.254,best_shift = (-6, 4)
best_scale=1.50, best_score=0.121,best_shift = (0, -4)
best_scale=1.55, best_score=0.186,best_shift = (-6, 4)
best_scale=1.55, best_score=0.171,best_shift = (0, -4)
best_scale=1.55, best_score=0.156,best_shift = (-6, 4)
best_scale=1.55, best_score=0.140,best_shift = (-2, -4)
best_scale=1.55, best_score=0.210,best_shift = (-8, 4)
best_scale=1.55, best_score=0.144,best_shift = (-6, 4)
best_scale=1.55, best_score=0.223,best_shift = (0, -4)
best_scale=1.60, best_score=0.202,best_shift = (-6, 4)
best_scale=1.55, best_score=0.186,best_shift = (-6, 6)
best_scale=1.50, best_score=0.147,best_shift = (0, -6)
best_scale=1.55, best_score=0.129,best_shift = (0, -6)
best_scale=1.55, best_score=0.218,best_shift = (0, -4)
best_scale=1.55, best_score=0.214,best_shift = (-8, 4)
best_scale=1.55, best_score=0.199,best_shift = (0, -4)
best_scale=1.55, best_score=0.167,best_shift = (-2, -4)
best_scale=1.55, best_score=0.233,best_shift = (-6, 4)
best_scale=1.55, best_score=0.181,best_shift = (-6, 4)
best_scale=1.55, best_score=0.176,best_shift = (0, -4)
best_scale=1.55, best_score=0.146,best_shift = (-8, 4)
best_scale=1.55, best_score=0.217,best_shift = (0, -4)
best_scale=1.55, best_score=0.176,best_shift = (-2, -4)
best_scale=1.55, best_score=0.246,best_shift = (-8, 4)
best_scale=1.60, best_score=0.199,best_shift = (-6, 4)
best_scale=1.50, best_score=0.162,best_shift = (0, -6)
best_scale=1.55, best_score=0.147,best_shift = (-6, 4)
best_scale=1.60, best_score=0.191,best_shift = (-6, 4)
best_scale=1.55, best_score=0.175,best_shift = (-2, -6)
best_scale=1.55, best_score=0.239,best_shift = (-6, 4)
best_scale=1.55, best_score=0.172,best_shift = (-8, 4)
best_scale=1.55, best_score=0.225,best_shift = (-6, 4)
best_scale=1.55, best_score=0.211,best_shift = (-6, 4)
best_scale=1.60, best_score=0.139,best_shift = (-6, 4)
best_scale=1.55, best_score=0.160,best_shift = (-6, 4)
best_scale=1.55, best_score=0.166,best_shift = (-8, 4)
best_scale=1.55, best_score=0.141,best_shift = (0, -6)
best_scale=1.55, best_score=0.116,best_shift = (0, -4)
best_scale=1.55, best_score=0.142,best_shift = (-2, -4)
best_scale=1.55, best_score=0.106,best_shift = (0, -4)
best_scale=1.55, best_score=0.289,best_shift = (0, -4)
best_scale=1.55, best_score=0.215,best_shift = (0, -4)
best_scale=1.55, best_score=0.145,best_shift = (0, -4)
best_scale=1.50, best_score=0.193,best_shift = (6, -6)
best_scale=1.55, best_score=0.183,best_shift = (-2, -6)
best_scale=1.60, best_score=0.249,best_shift = (-6, 4)
best_scale=1.55, best_score=0.127,best_shift = (0, -4)
best_scale=1.55, best_score=0.228,best_shift = (-2, -4)
best_scale=1.55, best_score=0.131,best_shift = (0, -4)
best_scale=1.55, best_score=0.192,best_shift = (-6, 4)
best_scale=1.55, best_score=0.193,best_shift = (-2, -4)
best_scale=1.55, best_score=0.172,best_shift = (-8, 4)
best_scale=1.55, best_score=0.200,best_shift = (-8, 4)
best_scale=1.55, best_score=0.200,best_shift = (0, -4)
best_scale=1.55, best_score=0.316,best_shift = (-6, 4)
best_scale=1.55, best_score=0.142,best_shift = (-8, 4)
best_scale=1.55, best_score=0.207,best_shift = (-2, -4)
best_scale=1.55, best_score=0.142,best_shift = (0, -4)
best_scale=1.55, best_score=0.185,best_shift = (-8, 4)
best_scale=1.55, best_score=0.138,best_shift = (-6, 6)
best_scale=1.55, best_score=0.205,best_shift = (0, -4)
best_scale=1.55, best_score=0.161,best_shift = (0, -4)
best_scale=1.55, best_score=0.162,best_shift = (0, -4)
best_scale=1.55, best_score=0.255,best_shift = (-2, -4)
best_scale=1.55, best_score=0.265,best_shift = (-6, 4)
best_scale=1.55, best_score=0.203,best_shift = (-8, 4)
best_scale=1.55, best_score=0.191,best_shift = (-2, -6)
best_scale=1.60, best_score=0.081,best_shift = (0, 4)
best_scale=1.55, best_score=0.194,best_shift = (-2, -4)
best_scale=1.55, best_score=0.197,best_shift = (0, -4)
best_scale=1.60, best_score=0.172,best_shift = (-8, 4)
best_scale=1.55, best_score=0.241,best_shift = (0, -4)
best_scale=1.55, best_score=0.183,best_shift = (-6, 4)
best_scale=1.55, best_score=0.207,best_shift = (-2, -4)
best_scale=1.55, best_score=0.162,best_shift = (-6, 4)
best_scale=1.55, best_score=0.196,best_shift = (0, -6)
best_scale=1.55, best_score=0.150,best_shift = (-6, 4)
best_scale=1.55, best_score=0.219,best_shift = (-2, -4)
best_scale=1.55, best_score=0.227,best_shift = (-6, 4)
best_scale=1.55, best_score=0.153,best_shift = (-2, -4)
best_scale=1.55, best_score=0.266,best_shift = (-8, 4)
best_scale=1.55, best_score=0.180,best_shift = (-8, 4)
best_scale=1.50, best_score=0.155,best_shift = (6, -6)
best_scale=1.60, best_score=0.200,best_shift = (-6, 4)
best_scale=1.55, best_score=0.165,best_shift = (0, -4)
best_scale=1.55, best_score=0.267,best_shift = (0, -4)
best_scale=1.55, best_score=0.153,best_shift = (0, -4)
best_scale=1.55, best_score=0.121,best_shift = (-8, 4)
best_scale=1.55, best_score=0.145,best_shift = (0, -4)
best_scale=1.55, best_score=0.191,best_shift = (-2, -6)
best_scale=1.60, best_score=0.189,best_shift = (-6, 4)
best_scale=1.55, best_score=0.164,best_shift = (0, -4)
best_scale=1.60, best_score=0.215,best_shift = (-6, 4)
best_scale=1.55, best_score=0.154,best_shift = (-2, -4)
best_scale=1.55, best_score=0.261,best_shift = (-6, 4)
best_scale=1.60, best_score=0.202,best_shift = (-6, 4)
best_scale=1.55, best_score=0.155,best_shift = (0, -4)
best_scale=1.55, best_score=0.151,best_shift = (-8, 4)
best_scale=1.50, best_score=0.165,best_shift = (6, -4)
best_scale=1.55, best_score=0.192,best_shift = (0, -4)
best_scale=1.50, best_score=0.150,best_shift = (0, -6)
best_scale=1.55, best_score=0.192,best_shift = (0, -4)
best_scale=1.55, best_score=0.147,best_shift = (0, -6)
best_scale=1.50, best_score=0.132,best_shift = (0, -6)
best_scale=1.55, best_score=0.183,best_shift = (-6, 4)
best_scale=1.55, best_score=0.178,best_shift = (-6, 4)
best_scale=1.55, best_score=0.337,best_shift = (0, -4)
best_scale=1.55, best_score=0.215,best_shift = (0, -4)
best_scale=1.55, best_score=0.113,best_shift = (-6, 4)
best_scale=1.55, best_score=0.166,best_shift = (0, -4)
best_scale=1.55, best_score=0.112,best_shift = (-2, -6)
best_scale=1.55, best_score=0.143,best_shift = (-2, -4)
best_scale=1.55, best_score=0.177,best_shift = (0, -4)
best_scale=1.55, best_score=0.176,best_shift = (-8, 4)
best_scale=1.50, best_score=0.084,best_shift = (-6, 0)
best_scale=1.55, best_score=0.199,best_shift = (-6, 4)
best_scale=1.55, best_score=0.109,best_shift = (0, -6)
best_scale=1.55, best_score=0.159,best_shift = (0, -4)
best_scale=1.60, best_score=0.156,best_shift = (-6, 4)
best_scale=1.55, best_score=0.198,best_shift = (8, -4)
best_scale=1.60, best_score=0.239,best_shift = (-6, 4)
best_scale=1.55, best_score=0.213,best_shift = (-2, -4)
best_scale=1.50, best_score=0.160,best_shift = (6, -6)
best_scale=1.55, best_score=0.281,best_shift = (-6, 4)
best_scale=1.55, best_score=0.253,best_shift = (-6, 4)
best_scale=1.60, best_score=0.199,best_shift = (-6, 4)
best_scale=1.55, best_score=0.141,best_shift = (-2, -4)
best_scale=1.55, best_score=0.307,best_shift = (-6, 4)
best_scale=1.55, best_score=0.149,best_shift = (-2, -4)
best_scale=1.55, best_score=0.307,best_shift = (-2, -4)
best_scale=1.55, best_score=0.109,best_shift = (0, -4)
best_scale=1.55, best_score=0.298,best_shift = (-2, -4)
best_scale=1.50, best_score=0.137,best_shift = (6, -6)
best_scale=1.50, best_score=0.151,best_shift = (6, -6)
best_scale=1.50, best_score=0.205,best_shift = (6, -6)
best_scale=1.50, best_score=0.185,best_shift = (6, -6)
best_scale=1.50, best_score=0.159,best_shift = (6, -6)
best_scale=1.55, best_score=0.178,best_shift = (4, -4)
best_scale=1.50, best_score=0.173,best_shift = (6, -6)
best_scale=1.50, best_score=0.159,best_shift = (6, -6)
best_scale=1.50, best_score=0.152,best_shift = (6, -6)
best_scale=1.50, best_score=0.171,best_shift = (6, -6)
best_scale=1.55, best_score=0.263,best_shift = (4, -4)
best_scale=1.50, best_score=0.112,best_shift = (6, -6)
best_scale=1.50, best_score=0.127,best_shift = (6, -6)
best_scale=1.50, best_score=0.201,best_shift = (6, -6)
best_scale=1.50, best_score=0.184,best_shift = (6, -6)
best_scale=1.50, best_score=0.204,best_shift = (6, -6)
best_scale=1.55, best_score=0.212,best_shift = (6, -4)
best_scale=1.50, best_score=0.195,best_shift = (6, -6)
best_scale=1.55, best_score=0.254,best_shift = (0, -4)
best_scale=1.55, best_score=0.102,best_shift = (4, -4)
best_scale=1.55, best_score=0.149,best_shift = (6, -4)
best_scale=1.50, best_score=0.210,best_shift = (6, -6)
best_scale=1.55, best_score=0.150,best_shift = (4, -4)
best_scale=1.50, best_score=0.161,best_shift = (6, -6)
best_scale=1.55, best_score=0.275,best_shift = (-2, -4)
best_scale=1.50, best_score=0.167,best_shift = (6, -6)
best_scale=1.55, best_score=0.233,best_shift = (-2, -4)
best_scale=1.55, best_score=0.284,best_shift = (0, -4)
best_scale=1.50, best_score=0.144,best_shift = (6, -6)
best_scale=1.50, best_score=0.162,best_shift = (-2, -6)
best_scale=1.55, best_score=0.133,best_shift = (0, -4)
best_scale=1.55, best_score=0.172,best_shift = (-2, -4)

In [ ]:
align_df = pd.DataFrame(align_data)

In [ ]:
data_scale_df = data_scale_df.merge(align_df, on='img_name', how='left', suffixes=('', '_a'))
for c in ['scale', 'score', 'loc']:
    data_scale_df[c] = data_scale_df[c + '_a'].combine_first(data_scale_df[c])
    data_scale_df.drop(columns=c + '_a', inplace=True)

In [142]:
data_scale_df.to_csv('new_full_fixed.csv')

In [ ]:
def draw_by_scale(img_orig, img_therm, best_scale, best_shift,vis_path="VI.jpg"):
    
    img_orig = cv2.imread(img_orig)
    img_therm = cv2.imread(img_therm)
    # GRAY
    g_therm = cv2.cvtColor(img_therm, cv2.COLOR_BGR2GRAY)
    h_t, w_t = g_therm.shape

    scaled = cv2.resize(img_orig, (int(img_orig.shape[1]/best_scale), int(img_orig.shape[0]/best_scale)))
    H, W = scaled.shape[:2]
    cx, cy = W // 2, H // 2
    dx,dy = best_shift
    x1 = cx - w_t//2 + dx
    y1 = cy - h_t//2 + dy
    x2, y2 = x1 + w_t, y1 + h_t
    best_aligned = scaled[y1:y2, x1:x2]
    
    overlay = cv2.addWeighted(best_aligned, 0.5, img_therm, 0.5, 0)
    concat = np.hstack((img_therm, best_aligned, overlay))
    cv2.imwrite(vis_path, concat)

In [151]:
img_orig = "D:\BODYPAR\Graphonomy\Graphonomy-master\img\P011_1_FLIR.jpg"
img_therm = "D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P011_1_thermal.jpg"
#1.55	0.176244	(-6, 4)
draw_by_scale(img_orig=img_orig,img_therm=img_therm,best_scale=1.55,best_shift=(-6,4))

In [ ]:
# apply outline to compare and match

In [ ]:
# to check the match
img_matchVis = r"D:\BODYPAR\Graphonomy\Graphonomy-master\img_matchvis"
def VisMatchResult(img_name, thermal_img,matched_img):
    
    loc = data_scale_df.loc[data_scale_df['img_name'] == img_name, 'loc'].values[0]
    x,y = loc
    scale = data_scale_df.loc[data_scale_df['img_name'] == img_name, 'scale'].values[0]

    outline = cv2.imread(matched_img)
    thermal = cv2.imread(thermal_img)
    h,w = thermal.shape[:2]
    h = int(h * scale)
    w = int(w * scale)
    x, y = int(x), int(y)
    thermal_resized = cv2.resize(thermal, (int(w ), int(h)))

    overlay = outline.copy()
    overlay[y:y+h, x:x+w] = thermal_resized

    alpha = 0.5
    roi = outline[y:y+h, x:x+w]
    blended = cv2.addWeighted(roi, 1-alpha, thermal_resized, alpha, 0)
    overlay[y:y+h, x:x+w] = blended
    vis_img = img_matchVis + f'\{img_name}' + 'matched.jpg'
    cv2.imwrite(vis_img, overlay)

In [ ]:
import ast
def crop_from_template_match(
    flir_path,
    thermal_path,
    best_scale,
    best_loc,
    out_path="flir_crop.png"
):
    flir = cv2.imread(flir_path)
    thermal = cv2.imread(thermal_path)

    Ht, Wt = thermal.shape[:2]
    if isinstance(best_loc, str):
        best_loc = ast.literal_eval(best_loc)


    x, y = map(int, best_loc)

    # scaled thermal 
    w = int(Wt * best_scale)
    h = int(Ht * best_scale)

    Hf, Wf = flir.shape[:2]
    x1 = max(0, x)
    y1 = max(0, y)
    x2 = min(Wf, x + w)
    y2 = min(Hf, y + h)

    if x1 >= x2 or y1 >= y2:
        raise ValueError("Empty crop from template match")

    roi = flir[y1:y2, x1:x2]

    # resize
    roi_resized = cv2.resize(roi, (Wt, Ht))

    cv2.imwrite(out_path, roi_resized)

In [ ]:
import cv2
import numpy as np

def crop_by_scale_and_shift(
    img_orig_path,
    img_therm_path,
    best_scale,
    best_shift,
    out_path="flir_crop_resized.png"
):
    img_orig = cv2.imread(img_orig_path)
    img_therm = cv2.imread(img_therm_path)

    h_t, w_t = img_therm.shape[:2]

    # resize
    scaled = cv2.resize(
        img_orig,
        (
            int(img_orig.shape[1] / best_scale),
            int(img_orig.shape[0] / best_scale)
        )
    )

    H, W = scaled.shape[:2]
    cx, cy = W // 2, H // 2

    if isinstance(best_shift, str):
        best_shift = ast.literal_eval(best_shift)
    dx, dy = map(int, best_shift)
    #crop box
    x1 = cx - w_t // 2 + dx
    y1 = cy - h_t // 2 + dy
    x2 = x1 + w_t
    y2 = y1 + h_t
    sx1 = max(0, x1)
    sy1 = max(0, y1)
    sx2 = min(W, x2)
    sy2 = min(H, y2)

    if sx1 >= sx2 or sy1 >= sy2:
        raise ValueError(f"Empty crop: shift={best_shift}, scale={best_scale}")

    tx1 = sx1 - x1
    ty1 = sy1 - y1
    tx2 = tx1 + (sx2 - sx1)
    ty2 = ty1 + (sy2 - sy1)

    
    cropped = np.zeros_like(img_therm)
    cropped[ty1:ty2, tx1:tx2] = scaled[sy1:sy2, sx1:sx2]

    cv2.imwrite(out_path, cropped)
    #return cropped

In [ ]:
img_orig = "D:\BODYPAR\Graphonomy\Graphonomy-master\img\P011_1_FLIR.jpg"
img_therm = "D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P011_1_thermal.jpg"
#1.55	0.176244	(-6, 4)

crop_by_scale_and_shift(
    img_orig,
    img_therm,
    1.55,
    (-6, 4),
    out_path="flir_crop_resized.png"
)

In [167]:
img_orig = "D:\BODYPAR\Graphonomy\Graphonomy-master\img\P010_1_FLIR.jpg"
img_therm = "D:\BODYPAR\Graphonomy\Graphonomy-master\img_thermal\P010_1_thermal.jpg"
#1.55	0.176244	(-6, 4)

crop_from_template_match(
    flir_path = img_orig,
    thermal_path= img_therm,
    best_scale = 1.552632,
    best_loc = (71, 46),
    out_path="flir_crop_resized.png"
)

In [33]:
img_crop = r"D:\BODYPAR\Graphonomy\Graphonomy-master\img_crop_par"
img_par = r"D:\BODYPAR\Graphonomy\Graphonomy-master\img_par"
data_scale = []
for image_name in data_scale_df['img_name'].tolist():
    #P010_1_FLIR_parsed.png
    image_name_flir = img_par + f'/{image_name}' +  '_FLIR_parsed_gray.png'
    image_name_thermal = f'{img_thermal}/' +  image_name + '_thermal.jpg'
    
    loc = data_scale_df.loc[data_scale_df['img_name'] == image_name, 'loc'].values[0]
    
    scale = data_scale_df.loc[data_scale_df['img_name'] == image_name, 'scale'].values[0]
    cropped_path = img_crop + f'\{image_name}_par_croped_gray.jpg'
    
    if image_name in fal_df['img_name'].unique().tolist():
        crop_by_scale_and_shift(
            image_name_flir,
            image_name_thermal,
            scale,
            loc,
            out_path=cropped_path
        )
    else:
        crop_from_template_match(
            flir_path = image_name_flir,
            thermal_path= image_name_thermal,
            best_scale =scale,
            best_loc = loc,
            out_path=cropped_path
        )

In [ ]:
# visualize the alignment

def visualize_crop_on_thermal(
    thermal_path,
    crop_path,
    out_path="vis.png",
    alpha=0.5
):
    thermal = cv2.imread(thermal_path)
    crop = cv2.imread(crop_path)

    if thermal is None or crop is None:
        raise ValueError("Failed to load images")

    if thermal.shape != crop.shape:
        raise ValueError(
            f"Shape mismatch: thermal {thermal.shape}, crop {crop.shape}"
        )

    # overlay
    overlay = cv2.addWeighted(
        thermal, 1 - alpha,
        crop, alpha,
        0
    )

    # concat
    vis = np.hstack([thermal, overlay, crop])

    cv2.imwrite(out_path, vis)

In [171]:
img_crop = r"D:\BODYPAR\Graphonomy\Graphonomy-master\img_crop1"
img_vi = r"D:\BODYPAR\Graphonomy\Graphonomy-master\match_temp"
data_scale = []
for image_name in data_scale_df['img_name'].tolist():
    image_name_crop = img_crop+ f'/{image_name}' +  '_croped.jpg'
    image_name_thermal = f'{img_thermal}/' +  image_name + '_thermal.jpg'
    image_name_vi = f'{img_vi}/' +  image_name + '_vi.jpg'
    visualize_crop_on_thermal(
        image_name_thermal,
        image_name_crop,
        out_path=image_name_vi,
        alpha=0.5
    )

In [5]:
data_scale_df.head()

   Unnamed: 0 img_name     scale     score       loc
0           0   P010_1  1.552632  0.414863  (71, 46)
1           1   P010_2  1.552632  0.254960  (70, 47)
2           2   P011_1  1.550000  0.176244   (-6, 4)
3           3   P011_2  1.500000  0.162467   (6, -6)
4           4   P012_1  1.550000  0.200189   (-6, 4)

In [15]:
fal_df.to_csv('fal_match.csv')

In [ ]:
img_crop = r"D:\BODYPAR\Graphonomy\Graphonomy-master\img_crop1_par"
data_scale = []
for image_name in data_scale_df['img_name'].tolist():
    image_name_flir = img_root+ f'/{image_name}' +  '_FLIR.jpg'
    image_name_thermal = f'{img_thermal}/' +  image_name + '_thermal.jpg'
    
    loc = data_scale_df.loc[data_scale_df['img_name'] == image_name, 'loc'].values[0]
    
    scale = data_scale_df.loc[data_scale_df['img_name'] == image_name, 'scale'].values[0]
    cropped_path = img_crop + f'\{image_name}_croped.jpg'
    
    if image_name in fal_df['img_name'].unique().tolist():
        # if the first alignment can't work -> change to the new alignment
        crop_by_scale_and_shift(
            image_name_flir,
            image_name_thermal,
            scale,
            loc,
            out_path=cropped_path
        )
    else:
        crop_from_template_match(
            flir_path = image_name_flir,
            thermal_path= image_name_thermal,
            best_scale =scale,
            best_loc = loc,
            out_path=cropped_path
        )

In [ ]:
# match body & color

In [15]:
import easyocr
reader = easyocr.Reader(['en'], gpu=False)
def ReadColorBar(path):
    img = cv2.imread(path)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    h, w, _ = img.shape
    colorbar = img_rgb[:, w-50:w, :]
    top_region = colorbar[0:50, :] 
    bottom_region = colorbar[-50:, :]
    top_result = reader.readtext(top_region)[0][1]
    bottom_result = reader.readtext(bottom_region)[0][1]
    return {'TopTemp':top_result,'BottomTemp':bottom_result}

Using CPU. Note: This module is much faster with a GPU.

In [ ]:
import easyocr
reader = easyocr.Reader(['en'], gpu=False)
def safe_read_text(reader, img):
    try:
        res = reader.readtext(img)
        if len(res) == 0:
            return None
        return res[0][1]
    except Exception as e:
        print("OCR failed:", e)
        return None


def ReadColorBar(path):
    img = cv2.imread(path)
    if img is None:
        raise ValueError("Image not found")

    h, w = img.shape[:2]

    # 色标在右侧
    colorbar = img[:, int(w*0.9):w]

    top_region = colorbar[0:50, :]
    bottom_region = colorbar[-50:, :]

    top_text = safe_read_text(reader, top_region)
    bottom_text = safe_read_text(reader, bottom_region)

    return {
        "TopTemp": top_text,
        "BottomTemp": bottom_text
    }

Using CPU. Note: This module is much faster with a GPU.

In [ ]:
import cv2
import numpy as np

def GetImageThermalByBodyPartFix(
    image_name,
    thermalImgPath,
    grayMaskPath,
    temp_max,
    temp_min
):
   

    try:
       
        thermal = cv2.imread(thermalImgPath)
        mask = cv2.imread(grayMaskPath)

        if thermal is None:
            print("Thermal image not found:", thermalImgPath)
            return None
        if mask is None:
            print("Mask image not found:", grayMaskPath)
            return None

        thermal = cv2.cvtColor(thermal, cv2.COLOR_BGR2RGB)
        mask = cv2.cvtColor(mask, cv2.COLOR_BGR2GRAY)

        h, w = mask.shape

        
        # Map temp -> Color

        thermal_gray = cv2.cvtColor(thermal, cv2.COLOR_RGB2GRAY)

        thermal_norm = thermal_gray / 255.0
        temp_map = temp_min + thermal_norm * (temp_max - temp_min)

    
        label_map = {
            1: "hat",
            2: "hair",
            4: "sunglasses",
            5: "upper_clothes",
            6: "dress",
            7: "coat",
            8: "socks",
            9: "pants",
            10: "jumpsuits",
            11: "scarf",
            12: "skirt",
            13: "face",
            14: "left_arm",
            15: "right_arm",
            16: "left_leg",
            17: "right_leg",
            18: "left_shoe",
            19: "right_shoe",
            20:"torso_skin"
        }

        result = {"image": image_name}

        # calculate the body part temperature
        for label_val, part_name in label_map.items():

            region_mask = (mask == label_val)

            if np.sum(region_mask) == 0:
                result[f"{part_name}_mean"] = np.nan
                result[f"{part_name}_max"] = np.nan
                result[f"{part_name}_min"] = np.nan
                
                result[f"{part_name}_p90"] = np.nan
                result[f"{part_name}_p10"] = np.nan
                result[f"{part_name}_std"] = np.nan
                continue

            temps = temp_map[region_mask]

            result[f"{part_name}_mean"] = float(np.mean(temps))
            result[f"{part_name}_max"] = float(np.max(temps))
            result[f"{part_name}_min"] = float(np.min(temps))
           
            result[f"{part_name}_p90"] = float(np.percentile(temps, 90))
            result[f"{part_name}_p10"] = float(np.percentile(temps, 10))
            result[f"{part_name}_std"] = float(np.std(temps, ddof=1))

    
        return result

    except Exception as e:
        print("Error in:", image_name)
        print(e)
        return None

In [ ]:
rows = []
output_df_el = pd.read_csv('bobody_part.csv')
for row in output_df_el.itertuples():
    image = row.image
    
    row = GetImageThermalByBodyPartFix(
        image,
        f"img_thermal/{image}_thermal.jpg",
        f"img_crop_par/{image}_par_croped_gray.jpg",
        temp_max = row.colorbar_max,
        temp_min = row.colorbar_min
    )

    if row is not None:
        rows.append(row)
    else:
        print("Skipped:", image)

temp_df = pd.DataFrame(rows)

d:\conda_envs\graphonomy_thermal\lib\site-packages\numpy\core\_methods.py:265: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
d:\conda_envs\graphonomy_thermal\lib\site-packages\numpy\core\_methods.py:257: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)